version: '3.8'
services:
  db:
    image: mariadb:10.4
    container_name: egov-db
    environment:
      MYSQL_ROOT_PASSWORD: password        # 루트 비번
      MYSQL_DATABASE: egovdb             # DB 이름
      MYSQL_USER: egovuser               # 유저
      MYSQL_PASSWORD: 1234           # 유저 비번
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  tomcat:
    image: tomcat:9-jdk11
    container_name: egov-tomcat
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ../target/egovApp-1.0.0.war:/usr/local/tomcat/webapps/ROOT.war


volumes:
  db_data: